  
[[redirects]]
  from = "/api/*"
  to = "http://wrx-test-162708929.us-east-2.elb.amazonaws.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
