[build]
  publish = "dist/"
  command = "sed -i \"s|API_PLACEHOLDER|${API_REDIRECT_URL}|g\" public/netlify.toml && npm run build"

[[redirects]]
  from = "/api/*"
  to = API_PLACEHOLDER
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

