# Name of workflow
name: Development workflow

# When workflow is triggered
on:
  push:
    branches:
      - main

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      # Run npm install and build on our code
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      # Deploy to Netlify using our dev secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          DEV_NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "DEV_NETLIFY_SITE_ID"]'