name: Test and Lint
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  # run_unit_test:
  #   name: Unit Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Setup Node.js 14
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14.x'
  #         cache: 'yarn'

  #     - name: Install dependencies
  #       run: yarn --frozen-lockfile

  #     - name: Run unit test
  #       run: yarn test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Linter
        run: yarn lint

